// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (title, metadata)
VALUES ($1, $2)
RETURNING id, title, created_at, updated_at, metadata
`

type CreateConversationParams struct {
	Title    *string `json:"title"`
	Metadata []byte  `json:"metadata"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.Title, arg.Metadata)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations
WHERE id = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversation, id)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, title, created_at, updated_at, metadata FROM conversations
WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT id, title, created_at, updated_at, metadata FROM conversations
ORDER BY updated_at DESC
LIMIT $1 OFFSET $2
`

type ListConversationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversation = `-- name: UpdateConversation :one
UPDATE conversations
SET title = $2, updated_at = NOW(), metadata = $3
WHERE id = $1
RETURNING id, title, created_at, updated_at, metadata
`

type UpdateConversationParams struct {
	ID       pgtype.UUID `json:"id"`
	Title    *string     `json:"title"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) UpdateConversation(ctx context.Context, arg UpdateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversation, arg.ID, arg.Title, arg.Metadata)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const updateConversationTimestamp = `-- name: UpdateConversationTimestamp :exec
UPDATE conversations
SET updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateConversationTimestamp(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateConversationTimestamp, id)
	return err
}
