// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, role, content, model, metadata, token_count, completion_time_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, conversation_id, role, content, model, created_at, metadata, token_count, completion_time_ms
`

type CreateMessageParams struct {
	ConversationID   pgtype.UUID `json:"conversation_id"`
	Role             string      `json:"role"`
	Content          string      `json:"content"`
	Model            *string     `json:"model"`
	Metadata         []byte      `json:"metadata"`
	TokenCount       *int32      `json:"token_count"`
	CompletionTimeMs *int32      `json:"completion_time_ms"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.Model,
		arg.Metadata,
		arg.TokenCount,
		arg.CompletionTimeMs,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.Model,
		&i.CreatedAt,
		&i.Metadata,
		&i.TokenCount,
		&i.CompletionTimeMs,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

const deleteMessagesByConversation = `-- name: DeleteMessagesByConversation :exec
DELETE FROM messages
WHERE conversation_id = $1
`

func (q *Queries) DeleteMessagesByConversation(ctx context.Context, conversationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessagesByConversation, conversationID)
	return err
}

const getConversationMessageCount = `-- name: GetConversationMessageCount :one
SELECT COUNT(*) FROM messages
WHERE conversation_id = $1
`

func (q *Queries) GetConversationMessageCount(ctx context.Context, conversationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getConversationMessageCount, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLatestMessageByConversation = `-- name: GetLatestMessageByConversation :one
SELECT id, conversation_id, role, content, model, created_at, metadata, token_count, completion_time_ms FROM messages
WHERE conversation_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestMessageByConversation(ctx context.Context, conversationID pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getLatestMessageByConversation, conversationID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.Model,
		&i.CreatedAt,
		&i.Metadata,
		&i.TokenCount,
		&i.CompletionTimeMs,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, conversation_id, role, content, model, created_at, metadata, token_count, completion_time_ms FROM messages
WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.Model,
		&i.CreatedAt,
		&i.Metadata,
		&i.TokenCount,
		&i.CompletionTimeMs,
	)
	return i, err
}

const listMessagesByConversation = `-- name: ListMessagesByConversation :many
SELECT id, conversation_id, role, content, model, created_at, metadata, token_count, completion_time_ms FROM messages
WHERE conversation_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMessagesByConversation(ctx context.Context, conversationID pgtype.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.Model,
			&i.CreatedAt,
			&i.Metadata,
			&i.TokenCount,
			&i.CompletionTimeMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByConversationPaginated = `-- name: ListMessagesByConversationPaginated :many
SELECT id, conversation_id, role, content, model, created_at, metadata, token_count, completion_time_ms FROM messages
WHERE conversation_id = $1
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type ListMessagesByConversationPaginatedParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

func (q *Queries) ListMessagesByConversationPaginated(ctx context.Context, arg ListMessagesByConversationPaginatedParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByConversationPaginated, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.Model,
			&i.CreatedAt,
			&i.Metadata,
			&i.TokenCount,
			&i.CompletionTimeMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
