// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Conversation struct {
	ID        pgtype.UUID        `json:"id"`
	Title     *string            `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Metadata  []byte             `json:"metadata"`
}

type Message struct {
	ID               pgtype.UUID        `json:"id"`
	ConversationID   pgtype.UUID        `json:"conversation_id"`
	Role             string             `json:"role"`
	Content          string             `json:"content"`
	Model            *string            `json:"model"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Metadata         []byte             `json:"metadata"`
	TokenCount       *int32             `json:"token_count"`
	CompletionTimeMs *int32             `json:"completion_time_ms"`
}
